/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b1747590a25a5980c1d1e0ec4beb44b2)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.wrangler/worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
