/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4869a2ef1757cceddc057ab664adb02c)
interface __BaseEnv_Env {
	PLATFORM_DB: D1Database;
	ASSETS: Fetcher;
	LVBT_DEPLOYMENT_ENV: "preview" | "production";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.wrangler/worker/index");
	}
	interface PreviewEnv {
		PLATFORM_DB: D1Database;
		ASSETS: Fetcher;
		LVBT_DEPLOYMENT_ENV: "preview";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "LVBT_DEPLOYMENT_ENV">> {}
}
