/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 70a57e3e961667f0690b7ce7ae589991)
interface __BaseEnv_Env {
	PLATFORM_DB: D1Database;
	LVBT_DEPLOYMENT_ENV: "preview" | "production";
	LVBT_DISCORD_SYNC_ENABLED: "false";
	LVBT_DISCORD_APPLICATION_ID: "";
	LVBT_DISCORD_GUILD_ID: "";
	LVBT_DISCORD_PRODUCTION_GUILD_ID: "";
	LVBT_DISCORD_MEMBER_ROLE_ID: "";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface PreviewEnv {
		PLATFORM_DB: D1Database;
		LVBT_DEPLOYMENT_ENV: "preview";
		LVBT_DISCORD_SYNC_ENABLED: "false";
		LVBT_DISCORD_APPLICATION_ID: "";
		LVBT_DISCORD_GUILD_ID: "";
		LVBT_DISCORD_PRODUCTION_GUILD_ID: "";
		LVBT_DISCORD_MEMBER_ROLE_ID: "";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "LVBT_DEPLOYMENT_ENV" | "LVBT_DISCORD_SYNC_ENABLED" | "LVBT_DISCORD_APPLICATION_ID" | "LVBT_DISCORD_GUILD_ID" | "LVBT_DISCORD_PRODUCTION_GUILD_ID" | "LVBT_DISCORD_MEMBER_ROLE_ID">> {}
}
