// /llms.txt — concise index for LLM crawlers, following the proposal at
// https://llmstxt.org. Hand-curated; the autogenerated counterpart lives
// at /llms-full.txt and pulls every doc, page, and project verbatim.
import type { APIRoute } from 'astro';
import { site } from '../lib/site';

export const prerender = true;

const u = (path: string): string => new URL(path, site.url).toString();

const body = `# ${site.name}

> ${site.tagline}

${site.name} is a Nevada nonprofit (EIN ${site.org.ein}, founded ${site.org.founded}) organizing for world-class public transit and supportive land use in the Las Vegas Valley. We're building toward the 2027 Nevada legislative session — the next window to win dedicated transit funding before the current bus system gets cut roughly in half.

## About
- [Home](${u('/')}): what we do, why now, and what's at stake for transit in Las Vegas
- [About](${u('/about')}): who we are, why we incorporated, and how the work is organized into educate / organize / advocate
- [Strategy](${u('/about/strategy')}): our theory of change — how we plan to win in Nevada
- [Vision](${u('/vision')}): the Las Vegas we're arguing for — trains, walkable streets, neighborhoods that don't require a car

## Work
- [Projects](${u('/projects')}): the public roadmap of active and planned projects
- [Events](${u('/events')}): upcoming events, talks, and organizing actions

## Take action
- [Get involved](${u('/join')}): newsletter, volunteer signup, and ways to plug in
- [Donate](${site.donate.url}): one-time and recurring gifts on GiveButter
- [Contact](${u('/contact')}): general, press, and partnership contacts

## Off-site
- [Instagram](${site.social.instagram}): @lasvegasfortransit
- [LinkedIn](${site.social.linkedin}): Las Vegans for Better Transit organization page
- [Bluesky](${site.social.bluesky}): @lasvegasfortransit.org
- [GitHub](https://github.com/LasVegasForTransit/website): the source of this website; we build in public

## Optional
- [Full content](${u('/llms-full.txt')}): every page, doc, and project as one markdown file
- [Sitemap](${u('/sitemap')}): human-readable directory of every public URL
- [Sitemap (XML)](${u('/sitemap-index.xml')}): machine-readable index for traditional crawlers
`;

export const GET: APIRoute = () =>
  new Response(body, {
    headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  });
