// /llms.txt — concise index for LLM crawlers, following the proposal at
// https://llmstxt.org. Hand-curated; the autogenerated counterpart lives
// at /llms-full.txt and pulls every doc, page, and project verbatim.
//
// Every line of the rendered output stays ≤ 80 characters so the file
// reads cleanly in a terminal and respects the convention common to
// other llms.txt examples in the wild. Bullet descriptions wrap onto
// 2-space-indented continuation lines so each list item stays a single
// markdown list item.
import type { APIRoute } from 'astro';
import { site } from '../lib/site';

export const prerender = true;

const u = (path: string): string => new URL(path, site.url).toString();

const body = `# ${site.name}

> ${site.tagline}

${site.name} is a Nevada nonprofit (founded ${site.org.founded})
organizing the public constituency that transit and land-use fights
in the Las Vegas Valley have never had. We educate Las Vegans on how
the regional transit system works, organize riders and supporters
into a coalition, and advocate at the Regional Transportation
Commission of Southern Nevada and in the Nevada Legislature for
world-class public transit and the land-use policy that makes
transit useful.

The Valley is the 14th-busiest bus network in the country with no
light rail, no dedicated transit funding source, and historically no
organized public voice. This site is where we publish what we
believe, what we're working on, and how to plug in.

The work runs across five initiatives:

- Public education — helping Las Vegans understand how transit and
  land use shape daily life in the Valley, in plain language and on
  the surfaces (social, print, in-person) where the public actually
  encounters them.
- Coalition building — connecting riders, labor, faith communities,
  students, businesses, and allied organizations into a constituency
  legislators have to answer to.
- Legislative advocacy — direct work with state and federal
  legislators, the RTC board, and municipal bodies on funding,
  policy, and specific transit and land-use projects.
- Research and accountability — data, reporting, ride audits, and an
  annual State of Transit publication on how the Valley's transit
  system actually performs.
- Youth engagement — connecting high school and college students to
  transit advocacy, both as the immediate beneficiaries of better
  mobility and as the long-term political base for the work.

## About
- [Home](${u('/')}): what we do, why it matters,
  and what's at stake for transit in Las Vegas
- [About](${u('/about')}): who we are, why we
  incorporated, and how the work is organized into educate /
  organize / advocate
- [Strategy](${u('/about/strategy')}): our
  theory of change — how we plan to win in Nevada

## Work
- [Projects](${u('/projects')}): the public
  roadmap of active and planned projects
- [Events](${u('/events')}): upcoming events,
  talks, and organizing actions

## Take action
- [Get involved](${u('/go')}): newsletter,
  volunteer signup, and ways to plug in
- [Donate](${site.donate.url}): one-time and recurring
  gifts on GiveButter
- [Contact](${u('/contact')}): general, press,
  and partnership contacts

## Off-site
- [Instagram](${site.social.instagram}):
  @lasvegasfortransit
- [LinkedIn](${site.social.linkedin}): Las
  Vegans for Better Transit organization page
- [Bluesky](${site.social.bluesky}):
  @lasvegasfortransit.org
- [GitHub](https://github.com/LasVegasForTransit/website): the source
  of this website; we build in public

## Optional
- [Full content](${u('/llms-full.txt')}): every
  page, doc, and project as one markdown file
- [Sitemap](${u('/sitemap')}): human-readable
  directory of every public URL
- [Sitemap (XML)](${u('/sitemap-index.xml')}):
  machine-readable index for traditional crawlers
`;

export const GET: APIRoute = () =>
  new Response(body, {
    headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  });
