// /llms.txt — concise index for LLM crawlers, following the proposal at
// https://llmstxt.org. Hand-curated; the autogenerated counterpart lives
// at /llms-full.txt and pulls every doc, page, and project verbatim.
//
// Every line of the rendered output stays ≤ 80 characters so the file
// reads cleanly in a terminal and respects the convention common to
// other llms.txt examples in the wild. Bullet descriptions wrap onto
// 2-space-indented continuation lines so each list item stays a single
// markdown list item.
import type { APIRoute } from 'astro';
import { site } from '../lib/site';

export const prerender = true;

const u = (path: string): string => new URL(path, site.url).toString();

// Lines whose URL comes from env (donate, socials) drop out entirely when the
// corresponding PUBLIC_LVBT_* var is unset — no dead links in the LLM index.
const takeAction = [
  `- [Get involved](${u('/go')}): newsletter,\n  volunteer signup, and ways to plug in`,
  site.donate.url &&
    `- [Donate](${site.donate.url}): one-time and recurring\n  gifts on GiveButter`,
  `- [Contact](${u('/contact')}): general, press,\n  and partnership contacts`,
]
  .filter(Boolean)
  .join('\n');

const offSite = [
  site.social.discord &&
    `- [Discord](${site.social.discord}): community chat\n  where volunteers coordinate and the organizing happens`,
  site.social.instagram && `- [Instagram](${site.social.instagram}):\n  @lasvegasfortransit`,
  site.social.linkedin &&
    `- [LinkedIn](${site.social.linkedin}): Las\n  Vegans for Better Transit organization page`,
  site.social.bluesky && `- [Bluesky](${site.social.bluesky}):\n  @lasvegasfortransit.org`,
  `- [GitHub](https://github.com/LasVegasForTransit/website): the source\n  of this website; we build in public`,
]
  .filter(Boolean)
  .join('\n');

const body = `# ${site.name}

> ${site.tagline}

${site.name} is a Nevada nonprofit (founded ${site.org.founded})
organizing the public constituency that transit and land-use fights
in the Las Vegas Valley have never had. We educate Las Vegans on how
the regional transit system works, organize riders and supporters
into a coalition, and build an advocacy presence at the Regional
Transportation Commission of Southern Nevada and, in the 2027
session, the Nevada Legislature — for world-class public transit
and the land-use policy that makes transit useful.

The Valley is the 14th-busiest bus network in the country with no
light rail, no dedicated transit funding source, and historically no
organized public voice. This site is where we publish what we
believe, what we're working on, and how to plug in.

The work runs across five initiatives:

- Public education — helping Las Vegans understand how transit and
  land use shape daily life in the Valley, in plain language and on
  the surfaces (social, print, in-person) where the public actually
  encounters them.
- Coalition building — connecting riders, labor, faith communities,
  students, businesses, and allied organizations into a constituency
  legislators have to answer to.
- Legislative advocacy — building relationships with state and
  federal legislators and showing up at the RTC board and municipal
  bodies on funding, policy, and specific transit and land-use
  projects.
- Research and accountability — data, reporting, ride audits, and an
  annual State of Transit publication on how the Valley's transit
  system actually performs.
- Youth engagement — connecting high school and college students to
  transit advocacy, as the people with the most to gain from better
  mobility and the longest stake in the work.

## About
- [Home](${u('/')}): what we do, why it matters,
  and what's at stake for transit in Las Vegas
- [About](${u('/about')}): who we are, why we
  incorporated, and how the work is organized into educate /
  organize / advocate
- [Strategy](${u('/about/strategy')}): our
  theory of change — how we plan to win in Nevada

## Work
- [Projects](${u('/projects')}): the public
  roadmap of active and planned projects
- [Events](${u('/events')}): upcoming events,
  talks, and organizing actions

## Take action
${takeAction}

## Off-site
${offSite}

## Optional
- [Full content](${u('/llms-full.txt')}): every
  page, doc, and project as one markdown file
- [Sitemap](${u('/sitemap')}): human-readable
  directory of every public URL
- [Sitemap (XML)](${u('/sitemap-index.xml')}):
  machine-readable index for traditional crawlers
`;

export const GET: APIRoute = () =>
  new Response(body, {
    headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  });
