// /llms-full.txt — autogenerated full-content dump for LLM crawlers.
// Pulls every doc, page, project, and initiative from the content
// collections at build time. The shorter index lives at /llms.txt.
//
// MDX bodies are emitted verbatim — they include component imports and
// JSX tags. LLMs handle this gracefully; we don't strip components here
// because doing so would also drop the descriptive prose inside them.
import type { APIRoute } from 'astro';
import { getCollection } from 'astro:content';
import { site } from '../lib/site';
import { byOrderThenTitle } from '../lib/projects';

export const prerender = true;

// Page-collection entry id → public URL. Docs that aren't directly routed
// (mission, problems, vision-doc, why-now) are included for content but
// don't get a Source line.
const pageRoutes: Record<string, string> = {
  home: '/',
  about: '/about',
  contact: '/contact',
  'get-involved': '/join',
};
const docRoutes: Record<string, string> = {
  strategy: '/about/strategy',
  vision: '/vision',
};

const u = (path: string): string => new URL(path, site.url).toString();

const fmtDate = (d: Date | undefined): string => (d ? d.toISOString().split('T')[0] : '');

export const GET: APIRoute = async () => {
  const [docs, pages, projects, initiatives] = await Promise.all([
    getCollection('docs'),
    getCollection('pages'),
    getCollection('projects'),
    getCollection('initiatives'),
  ]);

  const out: string[] = [];

  out.push(`# ${site.name} — full content`);
  out.push('');
  out.push(`> ${site.tagline}`);
  out.push('');
  out.push(`Source: ${site.url}`);
  out.push(`Generated: ${new Date().toISOString().split('T')[0]}`);
  out.push('');
  out.push(
    `${site.name} is a Nevada nonprofit (EIN ${site.org.ein}) organizing for public transit and supportive land use in the Las Vegas Valley. This file concatenates the full text of every doc, page, project, and initiative on the site so LLMs can ingest it in a single fetch.`,
  );
  out.push('');
  out.push('---');
  out.push('');

  // Top-level pages — copy that wraps the home, about, contact, and join layouts.
  out.push('# Pages');
  out.push('');
  for (const page of pages) {
    out.push(`## ${page.data.title}`);
    const route = pageRoutes[page.id];
    if (route) out.push(`Source: ${u(route)}`);
    if (page.data.summary) {
      out.push('');
      out.push(`> ${page.data.summary}`);
    }
    if (page.body) {
      out.push('');
      out.push(page.body.trim());
    }
    out.push('');
    out.push('---');
    out.push('');
  }

  // Long-form organizational docs — strategy, vision, mission, etc.
  out.push('# Organizational documents');
  out.push('');
  const sortedDocs = [...docs].sort((a, b) => (a.data.order ?? 999) - (b.data.order ?? 999));
  for (const doc of sortedDocs) {
    out.push(`## ${doc.data.title}`);
    const route = docRoutes[doc.id];
    if (route) out.push(`Source: ${u(route)}`);
    out.push(`Updated: ${fmtDate(doc.data.updated)}`);
    out.push('');
    out.push(`> ${doc.data.summary}`);
    if (doc.body) {
      out.push('');
      out.push(doc.body.trim());
    }
    out.push('');
    out.push('---');
    out.push('');
  }

  // Initiatives — the five categories projects are organized under.
  out.push('# Initiatives');
  out.push('');
  out.push(
    'Every project rolls up under one or more of these initiatives. They describe how the work is organized, not what it produces.',
  );
  out.push('');
  const sortedInits = [...initiatives].sort((a, b) => a.data.title.localeCompare(b.data.title));
  for (const init of sortedInits) {
    out.push(`## ${init.data.title}`);
    out.push('');
    out.push(init.data.description);
    out.push('');
  }
  out.push('---');
  out.push('');

  // Projects — frontmatter (status, dates, initiatives, tldr) + full body.
  out.push('# Projects');
  out.push('');
  out.push(
    `${projects.length} active and planned projects. Each project page tracks per-goal status (planned / in-progress / done) so the public roadmap reads as live commitments, not static aspiration.`,
  );
  out.push('');
  const sortedProjects = [...projects].sort(byOrderThenTitle);
  for (const project of sortedProjects) {
    out.push(`## ${project.data.title}`);
    out.push(`Source: ${u(`/projects/${project.id}`)}`);
    out.push(`Status: ${project.data.status}`);
    out.push(`Initiatives: ${project.data.initiatives.join(', ')}`);
    out.push(`Start: ${fmtDate(project.data.startDate)}`);
    if (project.data.endDate) out.push(`End: ${fmtDate(project.data.endDate)}`);
    out.push('');
    out.push(`> ${project.data.tldr}`);
    if (project.data.goals.length > 0) {
      out.push('');
      out.push('Goals:');
      for (const goal of project.data.goals) {
        const target = goal.target ? ` (target: ${fmtDate(goal.target)})` : '';
        out.push(`- [${goal.status}] ${goal.text}${target}`);
      }
    }
    if (project.body) {
      out.push('');
      out.push(project.body.trim());
    }
    out.push('');
    out.push('---');
    out.push('');
  }

  return new Response(out.join('\n'), {
    headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  });
};
